export type AppPage =
  | 'home'
  | 'expenses'
  | 'add-expense'
  | 'expense-detail'
  | 'common-fund'
  | 'settlements'
  | 'settlement-detail'
  | 'statistics'
  | 'settings'
  | 'recurring-expenses'
  | 'recurring-occurrence'
